UNEXPECTED_EVENTS = [
    {
        "event_id": "1",
        "event_type": "emotional_breakdown",
        "category": "emotional",
        "description": "被访者突然情绪失控（哭泣、愤怒、崩溃、焦虑或恐惧）",
        "possible_emotions": ["愤怒", "哭泣", "焦虑", "恐惧"],
    },
    {
        "event_id": "2",
        "event_type": "self_blame",
        "category": "emotional",
        "description": "被访者突然表达强烈自责或羞耻感",
        "possible_emotions": ["自责", "羞愧", "内疚"],
    },
    {
        "event_id": "3",
        "event_type": "topic_derailment",
        "category": "narrative",
        "description": "被访者严重偏离当前话题，长时间跑题",
        "possible_emotions": ["随意", "激动"],
    },
    {
        "event_id": "4",
        "event_type": "topic_refusal",
        "category": "narrative",
        "description": "被访者明确拒绝继续某一话题",
        "possible_emotions": ["防御", "不耐烦"],
    },
    {
        "event_id": "5",
        "event_type": "contradictory_information",
        "category": "narrative",
        "description": "被访者前后给出明显矛盾的信息",
        "possible_emotions": ["紧张", "犹豫"],
    },
    {
        "event_id": "6",
        "event_type": "question_misunderstanding",
        "category": "cognitive",
        "description": "被访者明显误解问题含义",
        "possible_emotions": ["困惑", "紧张"],
    },
    {
        "event_id": "7",
        "event_type": "factual_misconception",
        "category": "cognitive",
        "description": "被访者表达明显知识错误或迷信观点",
        "possible_emotions": ["笃信", "怀疑"],
    },
    {
        "event_id": "20",
        "event_type": "cognitive_limit",
        "category": "cognitive",
        "description": "被访者因年龄、文化水平或认知障碍无法理解复杂问题或清晰表达",
        "possible_emotions": ["无助", "尴尬", "沮丧"],
    },
    {
        "event_id": "21",
        "event_type": "memory_failure",
        "category": "cognitive",
        "description": "被访者无法回忆关键信息（时间、细节、数字）",
        "possible_emotions": ["懊恼", "困惑", "抱歉"],
    },
    {
        "event_id": "8",
        "event_type": "hostility_or_distrust",
        "category": "interpersonal",
        "description": "被访者对访谈员表现出敌意或不信任",
        "possible_emotions": ["怀疑", "愤怒"],
    },
    {
        "event_id": "9",
        "event_type": "role_reversal",
        "category": "interpersonal",
        "description": "被访者反客为主，质问访谈员个人立场",
        "possible_emotions": ["挑衅", "不满"],
    },
    {
        "event_id": "22",
        "event_type": "passive_noncooperation",
        "category": "interpersonal",
        "description": "被访者敷衍回答（如仅说“不知道”“随便”）",
        "possible_emotions": ["敷衍", "无聊", "抵触"],
    },
    {
        "event_id": "23",
        "event_type": "third_party_interference",
        "category": "interpersonal",
        "description": "被访者身边的人插话、干扰回答或频繁征求他人意见",
        "possible_emotions": ["犹豫", "依赖", "紧张"],
    },
    {
        "event_id": "10",
        "event_type": "self_harm_signal",
        "category": "ethical",
        "description": "被访者透露潜在自伤或他伤倾向",
        "possible_emotions": ["绝望", "无助"],
    },
    {
        "event_id": "11",
        "event_type": "illegal_request",
        "category": "ethical",
        "description": "被访者请求违法或明显不当的建议",
        "possible_emotions": ["急切", "投机"],
    },
    {
        "event_id": "24",
        "event_type": "sensitive_topic_resistance",
        "category": "ethical",
        "description": "被访者对隐私/敏感话题表现出强烈抵触",
        "possible_emotions": ["愤怒", "警惕", "羞耻"],
    },
    {
        "event_id": "12",
        "event_type": "questionnaire_critique",
        "category": "meta",
        "description": "被访者质疑问题设置本身的合理性",
        "possible_emotions": ["不满", "质疑"],
    },
    {
        "event_id": "13",
        "event_type": "early_termination_request",
        "category": "meta",
        "description": "被访者要求提前结束访谈",
        "possible_emotions": ["急躁", "疲惫"],
    },
    {
        "event_id": "25",
        "event_type": "pace_disruption",
        "category": "meta",
        "description": "被访者要求过快/过慢回答问题或频繁暂停",
        "possible_emotions": ["焦虑", "不耐烦", "谨慎"],
    },
    {
        "event_id": "14",
        "event_type": "disorganized_speech",
        "category": "communication",
        "description": "被访者语言混乱、时间线跳跃、重复或语法错误",
        "possible_emotions": ["困惑", "焦虑"],
    },
    {
        "event_id": "15",
        "event_type": "metaphorical_expression",
        "category": "communication",
        "description": "被访者大量使用隐喻或情绪化语言",
        "possible_emotions": ["担忧", "厌恶"],
    },
    {
        "event_id": "16",
        "event_type": "environmental_interruption",
        "category": "environmental",
        "description": "外部环境干扰（噪音/网络/设备/他人打断）",
        "possible_emotions": ["烦躁", "无奈", "着急"],
    },
    {
        "event_id": "17",
        "event_type": "sudden_logistics_request",
        "category": "environmental",
        "description": "被访者临时要求更换访谈地点/方式",
        "possible_emotions": ["警惕", "不安", "随意"],
    },
    {
        "event_id": "26",
        "event_type": "user_error_single_choice",
        "category": "user_error",
        "description": "单选题用户错误：给出不在选项内的答案，或一次性给出多个选项",
        "possible_emotions": ["困惑", "随意", "不确定"],
        "question_types": ["single_choice"],
    },
    {
        "event_id": "27",
        "event_type": "user_error_likert",
        "category": "user_error",
        "description": "量表题用户错误：用数字或自由文字回答，未按量表描述作答",
        "possible_emotions": ["随意", "不耐烦", "犹豫"],
        "question_types": ["Likert"],
    },
    {
        "event_id": "28",
        "event_type": "user_error_text_input",
        "category": "user_error",
        "description": "开放题用户错误：只给出极短回答或答非所问",
        "possible_emotions": ["敷衍", "疲惫", "心不在焉"],
        "question_types": ["text_input"],
    },
]

EVENT_INTENSITY = ["轻微", "中等", "强烈"]
EXPRESSION_STYLE = ["直接表达", "情绪化表达", "含蓄表达"]
